import { escapeHtml as e } from './content.mjs';
import { copy, learningPaths, referencePages } from './i18n.mjs';
export const repo = 'https://github.com/Pierreg99/AI-FOR-Everyone-Learn-Docs';
export const site = 'https://pierreg99.github.io/AI-FOR-Everyone-Learn-Docs/';
const shapes = {
  arrow: '<path d="M5 12h14m-6-6 6 6-6 6"/>',
  grid: '<rect x="3" y="3" width="7" height="7" rx="1.5"/><rect x="14" y="3" width="7" height="7" rx="1.5"/><rect x="3" y="14" width="7" height="7" rx="1.5"/><rect x="14" y="14" width="7" height="7" rx="1.5"/>',
  book: '<path d="M12 5v15M3 4h5a4 4 0 0 1 4 2 4 4 0 0 1 4-2h5v15h-5a4 4 0 0 0-4 2 4 4 0 0 0-4-2H3Z"/>',
  path: '<circle cx="5" cy="6" r="2"/><circle cx="19" cy="18" r="2"/><path d="M7 6h8a4 4 0 0 1 0 8H9a4 4 0 0 0 0 8"/>',
  lab: '<path d="M9 3h6m-5 0v6L4 19a1 1 0 0 0 1 2h14a1 1 0 0 0 1-2L14 9V3M7 15h10"/>',
  search: '<circle cx="10.5" cy="10.5" r="6.5"/><path d="m16 16 5 5"/>',
  bookmark: '<path d="M6 3h12v18l-6-4-6 4Z"/>',
  sun: '<circle cx="12" cy="12" r="4"/><path d="M12 2v2m0 16v2M2 12h2m16 0h2M5 5l1.5 1.5m11 11L19 19M5 19l1.5-1.5m11-11L19 5"/>',
  menu: '<path d="M4 6h16M4 12h16M4 18h16"/>',
  check: '<path d="m5 12 4 4L19 6"/>',
  code: '<path d="m8 6-6 6 6 6m8-12 6 6-6 6m-3-15-2 18"/>',
  external: '<path d="M14 3h7v7m0-7L10 14M10 3H3v18h18v-7"/>',
};
export const icon = (name, cls = '') =>
  `<svg class="icon ${cls}" width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.7" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true">${shapes[name] || shapes.book}</svg>`;
export const chapterUrl = (c, lang, root) =>
  `${root}docs/${lang}/${c.slug}.html`;
export function header(lang, root, alternate) {
  const t = copy[lang],
    home = `${root}${lang}/index.html`;
  return `<header class="topbar"><a class="brand" href="${home}" aria-label="AI for Everyone — ${e(t.overview)}"><img src="${root}assets/favicon.svg" width="35" height="35" alt=""><span>AI <span class="brand-light">for</span> Everyone<span class="brand-sub">${t.brandTagline}</span></span></a><nav class="topnav" aria-label="${e(t.overview)}"><a href="${home}#paths">${t.paths}</a><a href="${home}#library">${t.library}</a><a href="${home}#lab">${t.lab} <span class="new-dot"></span></a></nav><div class="top-actions"><nav class="languages" aria-label="Language / Sprache"><a href="${alternate.de}" lang="de" hreflang="de" ${lang === 'de' ? 'aria-current="page"' : ''}>DE</a><a href="${alternate.en}" lang="en" hreflang="en" ${lang === 'en' ? 'aria-current="page"' : ''}>EN</a></nav><button class="icon-button js-only" data-theme-toggle aria-label="${t.theme}" title="${t.theme}">${icon('sun')}</button><a class="github-top" href="${repo}">GitHub ${icon('external')}</a><button class="icon-button menu-button js-only" data-menu aria-expanded="false" aria-controls="sidebar" aria-label="${t.menu}">${icon('menu')}</button></div></header>`;
}
export function sidebar(lang, root, chapter) {
  const t = copy[lang],
    home = `${root}${lang}/index.html`;
  return `<aside class="sidebar" id="sidebar"><div><p class="nav-label">${t.space}</p><nav class="side-nav" aria-label="${t.space}">${[
    ['grid', 'overview', ''],
    ['path', 'paths', '#paths'],
    ['book', 'library', '#library'],
    ['lab', 'lab', '#lab'],
  ]
    .map(
      ([ic, key, hash]) =>
        `<a href="${home}${hash}"${!chapter && !hash ? ' class="selected" aria-current="page"' : ''}>${icon(ic)}${t[key]}${key === 'library' ? '<span class="nav-count">36</span>' : ''}</a>`,
    )
    .join(
      '',
    )}</nav><p class="nav-label curriculum-label">${t.curriculum}</p><nav class="track-nav" aria-label="${t.curriculum}">${t.tracks.map((name, i) => `<a href="${home}?track=${i}#library"${chapter?.track === i ? ' class="selected"' : ''}><span class="track-dot dot-${i}"></span><span>${name}</span><span class="nav-count">06</span></a>`).join('')}</nav><div class="side-reference"><a href="${root}docs/${lang}/glossary.html">${icon('book')}${t.resourceNames[1]}</a><a href="${root}docs/${lang}/sources.html">${icon('external')}${t.resourceNames[2]}</a></div></div><section class="progress-card js-only" aria-label="${t.progress}"><div class="progress-heading"><span>${t.progress}</span><strong data-progress-percent>0%</strong></div><progress max="36" value="0" data-progress aria-label="${t.progress}"></progress><p><span data-progress-count>0</span> / 36 ${t.completed}</p><a data-resume href="${root}docs/${lang}/01-ai-fundamentals.html">${t.resume} ${icon('arrow')}</a><small>${t.local}</small><details><summary>${t.manage}</summary><div class="backup-actions"><button class="text-button" data-export-progress>${t.exportProgress}</button><button class="text-button" data-import-progress>${t.importProgress}</button><input id="progress-import" type="file" accept="application/json,.json" hidden><small>${t.importHint}</small><button class="text-button" data-reset>${t.reset}</button></div></details></section></aside>`;
}
export function footer(lang, root) {
  const t = copy[lang];
  return `<footer class="footer"><div><strong>AI for Everyone<span class="tiny-dot"></span></strong><p>${t.footer}</p></div><div><a href="${repo}">${t.source} ↗</a><a href="${repo}/blob/main/${lang === 'de' ? 'CONTRIBUTING.de.md' : 'CONTRIBUTING.md'}">${t.contribute}</a><small>${t.privacy}</small></div></footer><nav class="mobile-dock" aria-label="${t.mobileNav}"><a href="${root}${lang}/index.html">${icon('grid')}<span>${t.overview}</span></a><a href="${root}${lang}/index.html#library">${icon('book')}<span>${t.library}</span></a><a class="js-only" href="${root}${lang}/index.html?bookmarks=1#library">${icon('bookmark')}<span>${t.bookmarks}</span></a><a class="js-only" href="${root}${lang}/index.html#lab">${icon('lab')}<span>${t.lab}</span></a></nav>`;
}
function heroArt(lang) {
  const t = copy[lang];
  return `<div class="hero-art" aria-hidden="true"><div class="art-top"><span class="status-dot"></span> ${t.artTitle} <span>01 / 36</span></div><svg viewBox="0 0 440 292" role="presentation"><defs><linearGradient id="chip" x1="0" y1="0" x2="1" y2="1"><stop stop-color="#a4f3ce"/><stop offset="1" stop-color="#38b49c"/></linearGradient><pattern id="dots" width="18" height="18" patternUnits="userSpaceOnUse"><circle cx="2" cy="2" r=".7" fill="#537e75" opacity=".5"/></pattern></defs><rect width="440" height="292" fill="url(#dots)"/><g stroke="#418373" fill="none"><path d="M75 93h60l44 44M358 76h-49l-48 59M70 220h65l43-46M360 216h-60l-38-44"/><circle cx="75" cy="93" r="5" fill="#90e7be"/><circle cx="358" cy="76" r="5" fill="#90e7be"/><circle cx="70" cy="220" r="5" fill="#90e7be"/><circle cx="360" cy="216" r="5" fill="#90e7be"/></g><path d="m139 174 80-47 82 47v25l-82 48-80-48Z" fill="#1b4b40" stroke="#548776"/><path d="m139 159 80-47 82 47v25l-82 48-80-48Z" fill="#286a56" stroke="#83cda9"/><path d="m139 145 80-47 82 47-82 48Z" fill="url(#chip)" stroke="#b6ffd8"/><path d="m157 145 62-36 64 36-64 37Z" fill="none" stroke="#17735b"/><text x="220" y="151" text-anchor="middle" fill="#144735" font-size="34" font-weight="800" font-family="system-ui">AI</text><g fill="#acd2c3" font-family="monospace" font-size="10" letter-spacing="2"><text x="31" y="75">${t.artContext}</text><text x="322" y="59">${t.artTools}</text><text x="29" y="249">${t.artMemory}</text><text x="311" y="246">${t.artVerify}</text></g></svg><div class="art-bottom"><span>${t.artModel} <b>+</b> ${t.artContext} <b>+</b> ${t.artTools}</span><span class="art-cross">${icon('grid')}</span></div></div>`;
}
export function homeBody(lang, root, chapters) {
  const t = copy[lang];
  return `<div class="page-wrap"><section class="creator-banner" aria-label="${e(t.creatorLabel)} Pierreg99"><a class="creator-identity" href="https://github.com/Pierreg99"><img src="${root}assets/pierreg99-logo.svg" width="56" height="56" alt=""><span><span class="creator-label">${e(t.creatorLabel)}</span><strong>Pierreg99 ${icon('external')}</strong></span></a><p><strong>AI for Everyone</strong><span>${e(t.creatorDescription)}</span></p></section><section class="hero" aria-labelledby="hero-title"><div class="hero-copy"><p class="eyebrow"><span class="tiny-dot"></span>${t.eyebrow}</p><h1 id="hero-title">${t.hero}<br><em>${t.heroAccent}</em></h1><p class="hero-lead">${t.intro}</p><div class="hero-actions"><a class="button primary" href="${chapterUrl(chapters[0], lang, root)}">${t.start} ${icon('arrow')}</a><a class="button subtle" href="#library">${t.explore}</a></div><p class="hero-note">${icon('check')}${t.heroNote}</p></div>${heroArt(lang)}</section><div class="stats-strip"><div><strong>36</strong><span>${t.chapters}</span></div><div><strong>DE <span>/</span> EN</strong><span>${t.languages}</span></div><div><strong>03</strong><span>${t.learningPaths}</span></div><div><span class="open-symbol">↗</span><span>${t.free}</span></div></div>
 <section class="learning-hub js-only" aria-label="${t.progress}"><div class="hub-copy"><p class="eyebrow">${t.journey}</p><h2 data-next-title>${e(chapters[0].locales[lang].title)}</h2><p data-journey-lead>${t.journeyLead}</p></div><div class="hub-stats"><strong data-progress-percent>0%</strong><span><span data-progress-count>0</span> / 36 ${t.completed}</span><span><span data-bookmark-count>0</span> ${t.savedCount}</span></div><a class="button primary" data-resume href="${chapterUrl(chapters[0], lang, root)}">${t.resume} ${icon('arrow')}</a></section>
 <section class="section" id="paths" aria-labelledby="paths-title"><p class="eyebrow">${t.pathEyebrow}</p><div class="section-heading"><h2 id="paths-title">${t.pathTitle}</h2></div><p class="section-lead">${t.pathLead}</p><div class="path-grid">${learningPaths.map((ids, i) => `<article class="path-card path-${i}"><div class="path-top"><span class="path-icon">${icon(['book', 'code', 'grid'][i])}</span><span class="path-level">${t.pathLevels[i]}</span><span class="path-number">0${i + 1}</span></div><h3>${t.pathNames[i]}</h3><p>${t.pathDescriptions[i]}</p><div class="path-meta">${ids.length} ${t.chapters} <span>·</span> ${ids.reduce((sum, id) => sum + chapters[id - 1].locales[lang].minutes, 0)} ${t.min}</div><div class="path-progress js-only"><div><span>${t.pathProgress}</span><strong data-path-count="${i}">0 / ${ids.length}</strong></div><progress data-path-progress="${i}" max="${ids.length}" value="0" aria-label="${t.pathNames[i]}: ${t.pathProgress}"></progress></div><a href="?path=${i}#library" class="path-link" data-path="${i}">${t.openPath} ${icon('arrow')}</a></article>`).join('')}</div></section>
 <section class="section library-section" id="library" aria-labelledby="library-title"><p class="eyebrow">${t.libraryEyebrow}</p><div class="section-heading"><h2 id="library-title">${t.libraryTitle}</h2><span class="outline-label">${t.updated}</span></div><p class="section-lead">${t.libraryLead}</p><noscript><p class="notice">${t.noScript}</p></noscript><div class="library-controls js-only"><div class="search-row"><label class="search-box" for="search">${icon('search')}<span class="sr-only">${t.search}</span><input id="search" type="search" placeholder="${t.searchPlaceholder}" autocomplete="off"><kbd>/</kbd></label><label class="sr-only" for="path-filter">${t.filterPath}</label><select id="path-filter"><option value="all">${t.allPaths}</option>${t.pathNames.map((n, i) => `<option value="${i}">${n}</option>`).join('')}</select></div><div class="filter-chips" role="group" aria-label="${t.curriculum}"><button data-filter="all" aria-pressed="true">${t.all}</button>${t.tracks.map((name, i) => `<button data-filter="${i}" aria-pressed="false">${name}</button>`).join('')}</div><div class="filter-details"><p id="result-count" role="status" aria-live="polite">36 ${t.results}</p><div><label><input type="checkbox" id="bookmarks-only"> ${t.onlyBookmarks}</label><label><input type="checkbox" id="unread-only"> ${t.unread}</label><label class="sr-only" for="sort">${t.sort}</label><select id="sort"><option value="number">${t.numerical}</option><option value="title">${t.alphabetical}</option></select></div></div></div><div class="chapter-grid" id="chapter-grid">${chapters.map((c) => chapterCard(c, lang, root)).join('')}</div><div class="empty-state" id="empty-state" hidden>${icon('search')}<h3>${t.empty}</h3><p>${t.emptyHelp}</p><button class="button" data-clear-filters>${t.clear}</button></div><button class="text-button clear-filter js-only" data-clear-filters>${t.clear}</button></section>
 ${labBody(lang)}
 <section class="section resources-section" id="resources" aria-labelledby="resources-title"><h2 id="resources-title">${t.resourcesTitle}</h2><div class="resource-grid">${referencePages.map((slug, i) => `<a class="resource-card" href="${root}docs/${lang}/${slug}.html"><div>${icon(i === 2 ? 'external' : 'book')}<span>0${i + 1}</span></div><h3>${t.resourceNames[i]} ${icon('arrow')}</h3><p>${t.resourceDescs[i]}</p></a>`).join('')}</div></section></div>`;
}
function chapterCard(c, lang, root) {
  const t = copy[lang],
    d = c.locales[lang];
  return `<article class="chapter-card" data-id="${c.id}"><div class="chapter-top"><span class="chapter-number">${String(c.id).padStart(2, '0')}</span><span class="chapter-category">${t.tracks[c.track]}</span><button class="icon-button bookmark-button js-only" data-bookmark="${c.id}" aria-pressed="false" aria-label="${t.bookmark}: ${e(d.title)}">${icon('bookmark')}</button></div><h3><a href="${chapterUrl(c, lang, root)}">${e(d.title)}</a></h3><p>${e(d.description)}</p><div class="chapter-bottom"><span>${d.minutes} ${t.min} <span class="complete-indicator" data-complete-indicator="${c.id}" hidden>· ${t.done} ✓</span></span><a href="${chapterUrl(c, lang, root)}" aria-label="${t.read}: ${e(d.title)}">${t.read} ${icon('arrow')}</a></div></article>`;
}
function labBody(lang) {
  const t = copy[lang];
  const numberField = (id, label, value, min, max, step = '1') =>
    `<label for="${id}">${label}<input id="${id}" type="number" min="${min}" max="${max}" step="${step}" value="${value}" inputmode="decimal" required></label>`;
  return `<section class="section lab-section js-only" id="lab" aria-labelledby="lab-title"><p class="eyebrow">${t.labEyebrow}</p><h2 id="lab-title">${t.labTitle}</h2><p class="section-lead">${t.labLead}</p><div class="architecture-lab"><div class="lab-tabs" role="tablist" aria-label="${t.lab}">${t.labModes.map((name, i) => `<button role="tab" id="lab-tab-${i}" data-lab="${i}" aria-controls="lab-panel" aria-selected="${i === 0}" tabindex="${i === 0 ? 0 : -1}">${name}</button>`).join('')}</div><div id="lab-panel" role="tabpanel" aria-labelledby="lab-tab-0"><div class="lab-flow" id="lab-flow"></div><div class="lab-detail" id="lab-detail" aria-live="polite"></div></div></div><div class="calculator-grid"><section class="calculator"><span class="mini-label">01 / ${t.costLabel}</span><h3>${t.calcTitle}</h3><p>${t.calcLead}</p><form id="cost-form" class="number-grid">${numberField('input-tokens', t.inTokens, 2000, 0, 10000000)}${numberField('output-tokens', t.outTokens, 500, 0, 10000000)}${numberField('input-price', t.inPrice, 2, 0, 100000, 'any')}${numberField('output-price', t.outPrice, 8, 0, 100000, 'any')}</form><div class="calculation-output"><output id="cost-result" for="input-tokens output-tokens input-price output-price" aria-live="polite">0.008</output><span>${t.calcResult}</span></div></section><section class="calculator"><span class="mini-label">02 / ${t.reliabilityLabel}</span><h3>${t.reliabilityTitle}</h3><p>${t.reliabilityNote}</p><form id="reliability-form" class="number-grid">${numberField('probability', t.probability, 95, 0, 100, 'any')}${numberField('steps', t.steps, 10, 1, 1000)}</form><div class="calculation-output"><output id="reliability-result" for="probability steps" aria-live="polite">59.9%</output><span>${t.chainResult}</span></div></section></div></section>`;
}
export function readerBody(
  doc,
  lang,
  root,
  rendered,
  chapter,
  chapters,
  filename,
) {
  const t = copy[lang],
    id = chapter?.id;
  const toolButtons = chapter
    ? `<button class="button primary js-only" data-complete="${id}" aria-pressed="false">${icon('check')}<span>${t.complete}</span></button><button class="button js-only" data-bookmark="${id}" aria-pressed="false" aria-label="${t.bookmark}: ${e(doc.title)}">${icon('bookmark')}<span>${t.bookmarks}</span></button>`
    : '';
  return `<div class="reading-progress js-only" role="progressbar" aria-label="${t.readingProgress}" aria-valuemin="0" aria-valuemax="100" aria-valuenow="0"><span></span></div><div class="page-wrap reader-wrap"><a class="back-link" href="${root}${lang}/index.html#library">← ${t.back}</a><div class="reader-heading"><p class="eyebrow">${id ? `${t.chapter} ${String(id).padStart(2, '0')} <span>/</span> ${t.tracks[chapter.track]}` : t.reference}</p><h1>${e(doc.title)}</h1><p class="reader-description">${e(doc.description)}</p><div class="reader-meta"><span>${doc.minutes} ${t.min} ${t.reading}</span><span>${t.updated}</span><span>${t.lang}</span></div></div><div class="reader-actions">${toolButtons}<button class="button focus-button js-only" data-focus aria-pressed="false" aria-keyshortcuts="f">${icon('book')}<span>${t.focus}</span></button><button class="text-button js-only" data-print>${t.print}</button><a class="text-link" href="${filename}.md">${t.markdown} ↗</a></div>${chapter ? `<div class="prerequisites"><strong>${t.prereqs}</strong> ${chapter.prerequisites.length ? chapter.prerequisites.map((n) => `<a href="${chapterUrl(chapters[n - 1], lang, root)}">${String(n).padStart(2, '0')} · ${e(chapters[n - 1].locales[lang].title)}</a>`).join('') : t.none}</div>` : ''}<details class="mobile-contents"><summary>${icon('menu')}${t.mobileContents}</summary><nav aria-label="${t.mobileContents}">${rendered.toc.map((h) => `<a href="#${h.id}">${e(h.text)}</a>`).join('')}</nav></details><div class="reader-layout"><article class="prose">${rendered.html}<div class="article-end"><a class="back-top" href="#main">${t.backTop} ↑</a><a href="${repo}/edit/main/docs/${lang}/${filename}.md">${t.edit} ${icon('external')}</a></div></article><aside class="toc"><p>${t.contents}</p><nav aria-label="${t.contents}">${rendered.toc.map((h) => `<a href="#${h.id}">${e(h.text)}</a>`).join('')}</nav></aside></div>${chapter ? `<nav class="chapter-pagination" aria-label="${t.chapters}">${id > 1 ? `<a href="${chapterUrl(chapters[id - 2], lang, root)}"><span>← ${t.prev}</span><strong>${e(chapters[id - 2].locales[lang].title)}</strong></a>` : '<span></span>'}${id < 36 ? `<a href="${chapterUrl(chapters[id], lang, root)}"><span>${t.next} →</span><strong>${e(chapters[id].locales[lang].title)}</strong></a>` : `<a href="${root}${lang}/index.html#library"><span>${t.back} →</span><strong>${t.library}</strong></a>`}</nav>` : ''}</div>`;
}
